/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./resources/js/Components/AppBar.vue')['default']
    AppDrawer: typeof import('./resources/js/Components/AppDrawer.vue')['default']
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    AuthenticatedLayout: typeof import('./resources/js/Layouts/AuthenticatedLayout/AuthenticatedLayout.vue')['default']
    ConfirmPassword: typeof import('./resources/js/Pages/Auth/ConfirmPassword.vue')['default']
    DashboardPage: typeof import('./resources/js/Pages/DashboardPage.vue')['default']
    DeleteUserForm: typeof import('./resources/js/Pages/Profile/Partials/DeleteUserForm.vue')['default']
    EditPage: typeof import('./resources/js/Pages/Profile/EditPage.vue')['default']
    ForgotPassword: typeof import('./resources/js/Pages/Auth/ForgotPassword.vue')['default']
    GuestLayout: typeof import('./resources/js/Layouts/GuestLayout.vue')['default']
    LoginPage: typeof import('./resources/js/Pages/Auth/LoginPage.vue')['default']
    MenuLinks: typeof import('./resources/js/Layouts/AuthenticatedLayout/Partials/MenuLinks.vue')['default']
    NavigationLinks: typeof import('./resources/js/Layouts/AuthenticatedLayout/Partials/NavigationLinks.vue')['default']
    RegisterPage: typeof import('./resources/js/Pages/Auth/RegisterPage.vue')['default']
    ResetPassword: typeof import('./resources/js/Pages/Auth/ResetPassword.vue')['default']
    UpdatePasswordForm: typeof import('./resources/js/Pages/Profile/Partials/UpdatePasswordForm.vue')['default']
    UpdateProfileInformationForm: typeof import('./resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue')['default']
    VerifyEmail: typeof import('./resources/js/Pages/Auth/VerifyEmail.vue')['default']
    WelcomePage: typeof import('./resources/js/Pages/WelcomePage.vue')['default']
  }
}
